@startuml
!include style.puml
skinparam ArrowFontStyle plain

participant ":ClearCommand" as ClearCommand LOGIC_COLOR
participant ":ModelManager" as ModelManager MODEL_COLOR

activate ClearCommand LOGIC_COLOR

ClearCommand -[LOGIC_COLOR]> ModelManager: clearSortedFilteredPersonsList()
activate ModelManager MODEL_COLOR

loop For each person in the displayed list
    ModelManager -[MODEL_COLOR]> ModelManager: deletePerson
    activate ModelManager MODEL_COLOR_T1
    ModelManager --[MODEL_COLOR]> ModelManager
    deactivate ModelManager

end loop

ModelManager --[LOGIC_COLOR]> ClearCommand
deactivate ModelManager

deactivate ClearCommand
@enduml

