@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR

package Logic as LogicPackage {

Class AddressBookParser
Class HistoryCommandParser
Class HistoryCommand
Class CommandResult
Class CommandHistory


LogicManager -right->"1" AddressBookParser
LogicManager -left->"1" CommandHistory
AddressBookParser -down..> HistoryCommandParser : creates >
HistoryCommandParser -down..> HistoryCommand : creates >
HistoryCommand -right..> CommandHistory
HistoryCommand -down-> CommandResult : produces >
@enduml
